//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATRACCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATRACCIONES()
        {
            this.ITINERARIOS = new HashSet<ITINERARIOS>();
        }
    
        public int idAtraccion { get; set; }
        public string nombreAtraccion { get; set; }
        public string direccionAtraccion { get; set; }
        public string descripcionAtraccion { get; set; }
        public string horarioAtraccion { get; set; }
        public string tarifaAtraccion { get; set; }
        public string serviciosAtraccion { get; set; }
        public string urlUbicacionAtraccion { get; set; }
        public string urlfotoAtraccion1 { get; set; }
        public string urlfotoAtraccion2 { get; set; }
        public string urlfotoAtraccion3 { get; set; }
        public Nullable<int> codPostal_Atraccion { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITINERARIOS> ITINERARIOS { get; set; }
    }
}
