//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHATS
    {
        public int idChat { get; set; }
        public Nullable<System.DateTime> fechaChat { get; set; }
        public string email { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string consulta { get; set; }
        public Nullable<int> idUsuario_Chat { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
