//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CIUDADES()
        {
            this.ATRACCIONES = new HashSet<ATRACCIONES>();
            this.HISTORIAL_CLIMATICO = new HashSet<HISTORIAL_CLIMATICO>();
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int codPostal { get; set; }
        public string descripcionCiudad { get; set; }
        public string nombreCiudad { get; set; }
        public string urlUbicacionCiudad { get; set; }
        public string urlfotoCiudad1 { get; set; }
        public string urlfotoCiudad2 { get; set; }
        public string urlfotoCiudad3 { get; set; }
        public Nullable<int> idDepartamento_ciudad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATRACCIONES> ATRACCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_CLIMATICO> HISTORIAL_CLIMATICO { get; set; }
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
