//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUDADES
    {
        public int idCiudad { get; set; }
        public int codPostal { get; set; }
        public string descripcionCiudad { get; set; }
        public string nombreCiudad { get; set; }
        public string urlUbicacionCiudad { get; set; }
        public string urlfotoCiudad1 { get; set; }
        public string urlfotoCiudad2 { get; set; }
        public string urlfotoCiudad3 { get; set; }
    }
}
