//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTAS_VIAEMAIL
    {
        public int idConsulta { get; set; }
        public string Nombre_Apellido { get; set; }
        public string email { get; set; }
        public long telefono { get; set; }
        public string motivoConsulta { get; set; }
        public string Mensaje { get; set; }
    }
}
