//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_CLIMATICO
    {
        public int idClima { get; set; }
        public Nullable<System.DateTime> fechaClima { get; set; }
        public string tempMin { get; set; }
        public string tempMax { get; set; }
        public string estadoClima { get; set; }
        public Nullable<int> codPostal_HistoClim { get; set; }
    
        public virtual CIUDADES CIUDADES { get; set; }
    }
}
