//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITINERARIOS()
        {
            this.ATRACCIONES = new HashSet<ATRACCIONES>();
        }
    
        public int idItinerario { get; set; }
        public string nombreItinerario { get; set; }
        public string descripcionItinerario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATRACCIONES> ATRACCIONES { get; set; }
    }
}
