//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDTursArgEntities : DbContext
    {
        public BDTursArgEntities()
            : base("name=BDTursArgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<ATRACCIONES> ATRACCIONES { get; set; }
        public virtual DbSet<CHATS> CHATS { get; set; }
        public virtual DbSet<CIUDADES> CIUDADES { get; set; }
        public virtual DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public virtual DbSet<HISTORIAL_CLIMATICO> HISTORIAL_CLIMATICO { get; set; }
        public virtual DbSet<ITINERARIOS> ITINERARIOS { get; set; }
        public virtual DbSet<PUBLICACIONES> PUBLICACIONES { get; set; }
        public virtual DbSet<TEMAS_DE_FORO> TEMAS_DE_FORO { get; set; }
    }
}
