//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMAS_DE_FORO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEMAS_DE_FORO()
        {
            this.PUBLICACIONES = new HashSet<PUBLICACIONES>();
        }
    
        public int idTema { get; set; }
        public string nombreDeTema { get; set; }
        public Nullable<int> idUserForo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICACIONES> PUBLICACIONES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
