//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TursArg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMAS_DE_FORO
    {
        public int idTema { get; set; }
        public string nombreDeTema { get; set; }
        public Nullable<int> idUserForo { get; set; }
        public Nullable<System.DateTime> fechaTema { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
    }
}
